### PR TITLE
Chapter 10 - bug/formatting fixes #87

### LINKED ISSUE #87: Chapter 10
- [ ] Case study formatting
- [ ] Missing key terms (bolded terms should be in key terms)
- [ ] In text references are hard coded and need to be dynamic.

### PR DESCRIPTION
**Pull request by natasha-sharma123**
Case study formated, missing key terms included, dynamic references @ect123 @pauldpickell

### CODE REVIEW

**Comment by pauldpickell** [comment]
You removed all the css formatting instead of just the case study. Please revert all other css elements to original except case study (e.g., learning objectives, recall this). 

When I knit this document, all of the figure numbers generate as `??` I think because bookdown treats plots created from code chunks differently from images like pngs that we use throughout most other parts of the textbook. So we need to modify how they are referenced. As an example, I managed to get this to knit correctly:

```{r 10-simple-random-sampling-2, echo=FALSE,warning=FALSE,fig.cap=fig_cap}
fig_cap <- paste0("Another simple random sample of 60 units. Nepal, CC-BY-SA-4.0.")
m <- matrix(c(1:625), nrow=25, ncol=25)
df2 <- expand.grid(x=1:ncol(m),y=1:nrow(m))
df2$val <- m[as.matrix(df[c('y','x')])]
n <- df2[sample(nrow(df2), 60, replace = FALSE, prob = NULL),]

p<-ggplot(n,aes(x=x, y=y, label=val)) + 
  geom_tile(data=df2, fill='transparent', colour = 'black') + 
  geom_tile(data=n,fill='black')+
  scale_y_reverse() +
  theme_classic() + 
  theme(axis.text  = element_blank(),
        panel.grid = element_blank(),
        axis.line  = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
p
```
Notice that I added `fig.cap=fig_cap` option at the top of the code chunk and then defined `fig_cap` as a text string that contains the figure caption text: `fig_cap <- paste0("Another simple random sample of 60 units. Nepal, CC-BY-SA-4.0.")` Then we can delete the line: `**Figure 10.2.** \ref{fig:figs} Another simple random sample of 60 units.` Basically what Sushil did was hard code a figure caption immediately after the plot, but we can ensure that figures are dynamically referenced and numbered by simply using the `fig.cap` option in the appropriate code chunk.

Another issue: you need to be careful about copy-pasting the figure reference without considering the context. For example, line 144 in your commit has the following `625 spatially defined plots as given in (Figure \@ref(fig:10-simple-random-sampling)).` which prints the following in the knitted document: `625 spatially defined plots as given in (Figure ??).` Please check all and ensure the parentheses are correct. Some figures will be referenced like `blah blah blah (Figure 10.1).` while others will be written like `blah blah blah, see Figure 10.1.` and the markdown reference needs to be adjusted accordingly.

Also, you missed the following figure: `...Rook’s case or Queen’s case Figure 10.10`.

**Comment by natasha-sharma123** [comment]
@pauldpickell By the css formatting do you mean the ".box-content .case-study-content" that was in line 451 and 453?

**Comment by natasha-sharma123** [comment]
@pauldpickell so in this screenshot, when I knit it, it shows the figure number. Is that not how it is supposed to look after the figure caption is changed to \ref ?
Screenshot 2022-02-18 104055

**Comment by ect123** [comment]
Closing because these issues are being resolved in a new branch

**Pull request closed without merging**
