### PR TITLE
Add lidar and emspectrum visualizations

### PR DESCRIPTION
**Pull request by kyjzhou**

### CODE REVIEW

**Comment by pauldpickell** [comment]
Okay, I see that this is for both the emspectrum and lidar visualizations. However, there are a lot of files in the lidar viz, apparently from potree, that are not needed for the viz. @jyoon008 Is it possible to reduce that overhead to only the necessary pieces to run potree for the lidar viz? I am looking at 550 files changes in this PR, some are pictures of cats or VR remotes.

**Comment by jyoon008** [comment]
@pauldpickell
Hi Paul, I had briefly scanned the application and know exactly the images and files you had mentioned.
Some of those files are fail-safes which allows the program to run in case of requirement errors: eg) background not set, default cat is displayed as the background. Others correspond to the features in Potree such as different languages. 
Here are the options if you would like to reduce the number of files:
#1) I am comfortable with removing 120 files which corresponds to icons and images.
#2) 195 files could be removed but this may have unanticipated effect on the visualization which we currently lack the resource to investigate.
Please let me know which options you'd prefer.

**Comment by pauldpickell** [comment]
@jyoon008 I noticed you removed some files, which is great. Last activity was two hours ago, are you done with this so that we can merge this PR? Also, what is the total size of the viz folder?

**Comment by pauldpickell** [comment]
We may reconsider this as it could make the dependency on potree difficult to merge upstream changes in the future if something dramatically changed. Could we install potree as a submodule instead, to make this process simpler in the future?

**Comment by jyoon008** [comment]
@pauldpickell Hi Paul, I had sent you an email regarding the number of files for the original code for LiDAR visualizations. Could you please let me know of your opinion? I would prefer not to delete any resources in the original code. Additionally, I am not familiar with the submodule feature on git so I don't have an opinion regarding that topic.

**Comment by ect123** [comment]
Thanks a ton @jyoon008 and others for this contribution. I just merged and tested locally for any major issues breaking the web and pdf builds of the book and didn't find any.

I think the next steps are for @pauldpickell and me to embed the visualizations into the book and configure captions and images for both interactive and static book builds. If this process unearths any unforeseen issues, then we will be back in touch! But for now I'm merging and closing this PR.

**Pull request merged**
